"""add order shipping and billing fields

Revision ID: 0e44af252095
Revises: 839d43876b4b
Create Date: 2026-08-17 12:05:30.072688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e44af252095'
down_revision = '839d43876b4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paypal_order_id', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('shipping_address', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('shipping_address2', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('shipping_postal_code', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('shipping_city', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('shipping_province', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('shipping_phone', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('billing_same_as_shipping', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('billing_address', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('billing_postal_code', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('billing_city', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('billing_province', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('billing_cif', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('billing_name', sa.String(length=150), nullable=True))
        batch_op.create_unique_constraint(None, ['paypal_order_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('billing_name')
        batch_op.drop_column('billing_cif')
        batch_op.drop_column('billing_province')
        batch_op.drop_column('billing_city')
        batch_op.drop_column('billing_postal_code')
        batch_op.drop_column('billing_address')
        batch_op.drop_column('billing_same_as_shipping')
        batch_op.drop_column('shipping_phone')
        batch_op.drop_column('shipping_province')
        batch_op.drop_column('shipping_city')
        batch_op.drop_column('shipping_postal_code')
        batch_op.drop_column('shipping_address2')
        batch_op.drop_column('shipping_address')
        batch_op.drop_column('paypal_order_id')

    # ### end Alembic commands ###
