"""guest checkout support order

Revision ID: 94ddf752b996
Revises: c0430529c15f
Create Date: 2026-08-20 14:34:22.342316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94ddf752b996'
down_revision = 'c0430529c15f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guest_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('guest_email', sa.String(length=120), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('guest_email')
        batch_op.drop_column('guest_name')

    # ### end Alembic commands ###
